name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas~=2.2.3
      - mlflow~=2.20.2
      - mlflow-skinny~=2.20.2
      - scikit-learn~=1.6.1
      - numpy~=2.1.3
      - xgboost~=2.1.4
      - scikit-optimize~=0.10.2
